/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Documents',
      items: [
        { type: 'autogenerated', dirName: '.' }
      ],
    },
  ],
};

module.exports = sidebars;
